default: |
  -c -r ./support -r ./coderdojo --expand --format pretty --format junit --out ./results/
  --format html --out results/index.html --format rerun --out ./results/rerun.txt

debug: DEBUG_MODE=true -p default

chrome: SELENIUM_BROWSER=chrome VIEW_IMPL=desktop_web -p default
headless-chrome: SELENIUM_BROWSER=headless-chrome VIEW_IMPL=desktop_web -p default
firefox: SELENIUM_BROWSER=firefox VIEW_IMPL=desktop_web -p default
opera: SELENIUM_BROWSER=opera VIEW_IMPL=desktop_web -p default
safari: SELENIUM_BROWSER=safari VIEW_IMPL=desktop_web -p default
